# 1. Redirigir a los despistados: Si alguien entra sin poner "https", le obligamos a usarlo.
<VirtualHost *:80>
    ServerName imad-proyecto-redes.duckdns.org
    Redirect permanent / https://imad-proyecto-redes.duckdns.org/
</VirtualHost>

# 2. Tu servidor principal blindado con el candado verde
<VirtualHost *:443>
    ServerName imad-proyecto-redes.duckdns.org

    # Aquí le decimos dónde guardaste el DNI de DuckDNS
    SSLEngine on
    SSLCertificateFile /etc/letsencrypt/live/imad-proyecto-redes.duckdns.org/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/imad-proyecto-redes.duckdns.org/privkey.pem

    # MODO CHIVATO ACTIVADO: Nos dirá exactamente por qué falla el LDAP
    LogLevel debug

    # --- Ruteo de los Contenedores ---
    ProxyPass /php http://php/
    ProxyPassReverse /php http://php/

    ProxyPass /tomcat http://tomcat:8080/
    ProxyPassReverse /tomcat http://tomcat:8080/

    # --- Zona Segura LDAP ---
    <Location /privado>
        AuthType Basic
        AuthName "Acceso Administradores"
        AuthBasicProvider ldap

        AuthLDAPURL "ldap://10.0.1.139:389/dc=example,dc=org?cn?sub?(objectClass=*)"
        AuthLDAPBindDN "cn=admin,dc=example,dc=org"
        AuthLDAPBindPassword "admin"
        Require valid-user
    </Location>

    # El Frontend (Ruta por defecto)
    ProxyPass / http://frontend/
    ProxyPassReverse / http://frontend/
</VirtualHost>
